# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-05 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20201104_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='neighbourhood',
        ),
    ]
